export const fallbackTutors = [
  {
    id: 1784801759175,
    name: 'Sachin Kumar',
    age: 42,
    experience: 20,
    subject: 'Mathematics',
    topics: ['Algebra', 'Mensuration'],
    hourlyRate: 300,
    photo: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 101,
    name: 'Maya Iyer',
    age: 29,
    experience: 6,
    subject: 'Mathematics',
    topics: ['Algebra', 'Trigonometry', 'Calculus'],
    hourlyRate: 300,
    photo: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 102,
    name: 'Ravi Nair',
    age: 31,
    experience: 8,
    subject: 'Science',
    topics: ['Physics', 'Chemistry', 'Biology'],
    hourlyRate: 400,
    photo: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 103,
    name: 'Sneha Joshi',
    age: 27,
    experience: 4,
    subject: 'Mathematics',
    topics: ['Statistics', 'Probability', 'Mensuration'],
    hourlyRate: 200,
    photo: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 104,
    name: 'Anirban Sen',
    age: 35,
    experience: 10,
    subject: 'Science',
    topics: ['Modern Physics', 'Electrochemistry', 'Human Physiology'],
    hourlyRate: 500,
    photo: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 105,
    name: 'Parul Kaur',
    age: 26,
    experience: 3,
    subject: 'Mathematics',
    topics: ['Geometry', 'Algebra', 'Vectors'],
    hourlyRate: 250,
    photo: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 106,
    name: 'Devansh Rao',
    age: 33,
    experience: 7,
    subject: 'Science',
    topics: ['Light', 'Electricity', 'Motion'],
    hourlyRate: 350,
    photo: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=crop&w=800&q=80',
  },
]

export const fallbackStudents = [
  { id: 201, name: 'Aarav Mehta', classLevel: '10', topic: 'Algebra', offerRate: 250, email: 'aarav@demo.com' },
  { id: 202, name: 'Naina Singh', classLevel: '9', topic: 'Geometry', offerRate: 220, email: 'naina@demo.com' },
  { id: 203, name: 'Kabir Patel', classLevel: '12', topic: 'Calculus', offerRate: 300, email: 'kabir@demo.com' },
  { id: 204, name: 'Meera Rao', classLevel: '11', topic: 'Chemistry', offerRate: 260, email: 'meera@demo.com' },
  { id: 205, name: 'Tanishq Das', classLevel: '10', topic: 'Probability', offerRate: 240, email: 'tanishq@demo.com' },
  { id: 206, name: 'Sakshi Gupta', classLevel: '9', topic: 'Mensuration', offerRate: 210, email: 'sakshi@demo.com' },
  { id: 207, name: 'Vikram Jain', classLevel: '12', topic: 'Modern Physics', offerRate: 320, email: 'vikram@demo.com' },
  { id: 208, name: 'Pooja Menon', classLevel: '11', topic: 'Biology', offerRate: 270, email: 'pooja@demo.com' },
  { id: 209, name: 'Aditya Chawla', classLevel: '10', topic: 'Trigonometry', offerRate: 230, email: 'aditya@demo.com' },
  { id: 210, name: 'Ritika Sharma', classLevel: '12', topic: 'Electrochemistry', offerRate: 290, email: 'ritika@demo.com' },
  { id: 211, name: 'Harshit Rawat', classLevel: '9', topic: 'Number Systems', offerRate: 200, email: 'harshit@demo.com' },
  { id: 212, name: 'Divya Kapoor', classLevel: '11', topic: 'Statistics', offerRate: 240, email: 'divya@demo.com' },
]

export const fallbackBookings = []
